# Generated by Django 3.2.3 on 2021-05-19 04:38

import classifier.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_user_mail_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file_name', models.CharField(max_length=250)),
                ('file', models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\abhis\\Downloads\\Assignments\\Interviews\\Singularity Systems\\Project\\model/queue'), upload_to=classifier.models.save_uploaded_file)),
                ('parsed_file_name', models.CharField(default='Uploaded_file', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
