# Generated by Django 3.2.3 on 2021-05-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='prediction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
